// @vitest-environment jsdom
import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {MemoryRouter} from 'react-router-dom';
import {finalCapability,finalEnvelope,finalRequest} from '../../test/finalDecisionFixture';
import {adaptFinalDecision} from '../../providers/decision/finalAdapter';
import {FinalDecisionInput} from './FinalDecisionInput';
import {FormalStressExperiment} from './FormalStressExperiment';
import {DecisionSummary} from './DecisionResultView';
import {RangePlot,rangeDomain} from './DecisionVisuals';
import {actualProfit,shownConfidence} from './presentation';
import type {DecisionProvider,StressScenario} from '../../domain/decision/types';

beforeEach(()=>vi.stubGlobal('matchMedia',()=>({matches:true,addListener:vi.fn(),removeListener:vi.fn(),addEventListener:vi.fn(),removeEventListener:vi.fn()})));
afterEach(()=>{cleanup();vi.unstubAllGlobals();});
const empty:StressScenario={id:'custom',label:'压力情景',changes:{price_pct:-20,yield_pct:0,cost_pct:0,delay_days:0},profit:{unit:'CNY',low:null,base:null,high:null,semantics:'model_scenario',is_calibrated_interval:false,is_mock:false},roi:null,delta_cny:null,is_mock:false,note:'正式模型暂不提供此估算。'};
describe('formal UI semantics',()=>{
  it('price axis uses observed range; money and ROI retain zero',()=>{expect(rangeDomain([3,4,5],'CNY/kg').lower).toBeGreaterThan(0);expect(rangeDomain([100,200],'CNY').lower).toBeLessThan(0);expect(rangeDomain([-.1,-.2],'ratio').upper).toBeGreaterThan(0);});
  it('price chart has no zero marker, profit chart has one',()=>{const c=adaptFinalDecision(finalEnvelope()).candidates[0];const {container,rerender}=render(<RangePlot title="价格" rows={[{label:'价格',range:c.price}]}/>);expect(container.querySelector('.decision-plot__zero')).toBeNull();rerender(<RangePlot title="收益" rows={[{label:'收益',range:c.profit}]}/>);expect(container.querySelector('.decision-plot__zero')).not.toBeNull();});
  it('missing/proxy profit is secondary and chosen confidence is source overall',()=>{const result=adaptFinalDecision(finalEnvelope());const c=result.candidates[0];expect(actualProfit(c)).toBe(false);expect(shownConfidence(result,c)).toBe(c.confidence);const {container}=render(<MemoryRouter><DecisionSummary result={result} candidate={c} onDetail={()=>{}} onCompare={()=>{}} onEvidence={()=>{}} stressUrl="/scenario-lab"/></MemoryRouter>);expect(container.querySelector('.decision-result__range')?.textContent).toContain('元/kg');expect(container.querySelectorAll('.decision-confidence')).toHaveLength(1);});
  it('unsupported city prevents form submission before user inputs',async()=>{const provider:DecisionProvider={data_mode:'api',decide:vi.fn(),capabilities:async()=>({...finalCapability('dalian'),supported:false,crops:[],market_as_of:null})};render(<FinalDecisionInput cityId="dalian" provider={provider} initial={null} onSubmit={vi.fn()}/>);await screen.findByText('这个城市暂不支持种植决策');expect(screen.queryByRole('button',{name:'比较种植选择 →'})).toBeNull();});
  it('submits canonical crops, optional climate date and scenario horizon',async()=>{const submit=vi.fn();const provider:DecisionProvider={data_mode:'api',decide:vi.fn(),capabilities:async()=>finalCapability()};const {container}=render(<FinalDecisionInput cityId="shenyang" provider={provider} initial={null} onSubmit={submit}/>);await screen.findByRole('button',{name:'比较种植选择 →'});fireEvent.change(container.querySelector('[name="area"]')!,{target:{value:'60'}});fireEvent.change(container.querySelector('[name="budget"]')!,{target:{value:'30'}});fireEvent.change(container.querySelector('[name="horizon"]')!,{target:{value:'90'}});fireEvent.click(screen.getByLabelText('西红柿'));fireEvent.click(screen.getByRole('button',{name:'比较种植选择 →'}));expect(submit).toHaveBeenCalledOnce();expect(submit.mock.calls[0][0].user_context.market_context).toEqual({as_of:'2026-09-14',horizon_days:90,harvest_date:null});expect(submit.mock.calls[0][0].user_context.crop_preferences).toEqual(['西红柿']);});
  it('rejects stale unsupported crop preference rather than silently changing it',async()=>{const r=finalRequest();r.user_context.crop_preferences=['番茄'];const submit=vi.fn();render(<FinalDecisionInput cityId="shenyang" provider={{decide:vi.fn(),capabilities:async()=>finalCapability()}} initial={r} onSubmit={submit}/>);await screen.findByRole('button',{name:'比较种植选择 →'});fireEvent.click(screen.getByRole('button',{name:'比较种植选择 →'}));expect(submit).not.toHaveBeenCalled();expect(screen.getByRole('alert').textContent).toContain('支持的作物名称');});
});
describe('formal stress authority',()=>{
  function mount(stress?:DecisionProvider['stress']){const r=finalRequest();const c=adaptFinalDecision(finalEnvelope()).candidates[0];render(<MemoryRouter><FormalStressExperiment candidate={c} request={r} provider={{data_mode:'api',decide:vi.fn(),stress}}/></MemoryRouter>);return {r,c};}
  it('calls provider for preset and never fills missing profit with formula',async()=>{const stress=vi.fn().mockResolvedValue(empty);const {r,c}=mount(stress);fireEvent.click(screen.getByRole('button',{name:'市场转弱'}));await screen.findByText('正式模型暂不提供此估算。');expect(stress).toHaveBeenCalledWith(r,c,empty.changes,expect.objectContaining({signal:expect.any(AbortSignal)}));expect(screen.getByRole('heading',{name:'基准净收益 —'})).toBeTruthy();expect(screen.queryByText('公式演示')).toBeNull();});
  it('uses model severe combo with yield -15%, preserving official combination',async()=>{const stress=vi.fn().mockResolvedValue({...empty,changes:{price_pct:-20,yield_pct:-15,cost_pct:20,delay_days:0}});mount(stress);fireEvent.click(screen.getByRole('button',{name:'综合压力'}));await waitFor(()=>expect(stress).toHaveBeenCalled());expect(stress.mock.calls[0][2].yield_pct).toBe(-15);});
  it('missing formal provider is unavailable rather than formula',async()=>{mount();fireEvent.click(screen.getByRole('button',{name:'市场转弱'}));await screen.findByRole('alert');expect(screen.getByRole('heading',{name:'基准净收益 —'})).toBeTruthy();});
  it('aborts prior scenario and ignores late response',async()=>{let resolve!:(v:StressScenario)=>void;const stress=vi.fn().mockImplementationOnce(()=>new Promise<StressScenario>(r=>{resolve=r;})).mockResolvedValueOnce({...empty,note:'第二组正式结果'});mount(stress);fireEvent.click(screen.getByRole('button',{name:'市场转弱'}));await waitFor(()=>expect(stress).toHaveBeenCalledTimes(1));const signal=stress.mock.calls[0][3].signal;fireEvent.click(screen.getByRole('button',{name:'生产受损'}));await screen.findByText('第二组正式结果');expect(signal.aborted).toBe(true);resolve({...empty,note:'迟到结果'});await Promise.resolve();expect(screen.queryByText('迟到结果')).toBeNull();});
});
